palette:
  top: '#4c1c58'
  bottom: '#593662'
  bg: '#fffdf7'
  sidebar: '#edede7'
  sidebarborders: '#e7e7e7'
  footer: '#2c2c28'
  button: '#9d408d'
  buttonhover: '#77316b'
  titleslogan: '#ffffff'
  text: '#301313'
  link: '#9d408d'
logo: 'public://color/build_house-6f3a4309/logo.svg'
stylesheets:
  - 'public://color/build_house-6f3a4309/colors.css'
files:
  - 'public://color/build_house-6f3a4309/logo.svg'
  - 'public://color/build_house-6f3a4309/colors.css'
